// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"index-cn/index":{"path":"index-cn","id":"index-cn/index","parentId":"DocLayout"},"index/index":{"path":"","id":"index/index","parentId":"DocLayout"},"docs/spec/introduce.zh-CN":{"path":"docs/spec/introduce-cn","id":"docs/spec/introduce.zh-CN","parentId":"DocLayout"},"docs/resources.zh-CN":{"path":"docs/resources-cn","id":"docs/resources.zh-CN","parentId":"DocLayout"},"docs/spec/test":{"path":"docs/spec/test","id":"docs/spec/test","parentId":"DocLayout"},"components/button/index.zh-CN":{"id":"components/button/index.zh-CN","path":"components/button-cn","parentId":"DocLayout","meta":{"_atom_route":true}},"components/iconselect/index.zh-CN":{"id":"components/iconselect/index.zh-CN","path":"components/iconselect-cn","parentId":"DocLayout","meta":{"_atom_route":true}},"components/inputnumber/index.zh-CN":{"id":"components/inputnumber/index.zh-CN","path":"components/inputnumber-cn","parentId":"DocLayout","meta":{"_atom_route":true}},"components/overview/index.zh-CN":{"id":"components/overview/index.zh-CN","path":"components/overview-cn","parentId":"DocLayout","meta":{"_atom_route":true}},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/xiaozisong/Desktop/opensource/amenity-ui/node_modules/.pnpm/dumi@2.3.0-beta.8_borxkdqnsj666zm5xafhs5jqdq/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/xiaozisong/Desktop/opensource/amenity-ui/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "dumi__theme__layouts__DocLayout__index" */'/Users/xiaozisong/Desktop/opensource/amenity-ui/.dumi/theme/layouts/DocLayout/index.tsx')),
'index-cn/index': React.lazy(() => import(/* webpackChunkName: "dumi__pages__index-cn__index" */'/Users/xiaozisong/Desktop/opensource/amenity-ui/.dumi/pages/index-cn/index.tsx')),
'index/index': React.lazy(() => import(/* webpackChunkName: "dumi__pages__index__index" */'/Users/xiaozisong/Desktop/opensource/amenity-ui/.dumi/pages/index/index.tsx')),
'docs/spec/introduce.zh-CN': React.lazy(() => import(/* webpackChunkName: "docs__spec__introduce.zh-CN.md" */'/Users/xiaozisong/Desktop/opensource/amenity-ui/docs/spec/introduce.zh-CN.md')),
'docs/resources.zh-CN': React.lazy(() => import(/* webpackChunkName: "docs__resources.zh-CN.md" */'/Users/xiaozisong/Desktop/opensource/amenity-ui/docs/resources.zh-CN.md')),
'docs/spec/test': React.lazy(() => import(/* webpackChunkName: "docs__spec__test.md" */'/Users/xiaozisong/Desktop/opensource/amenity-ui/docs/spec/test.md')),
'components/button/index.zh-CN': React.lazy(() => import(/* webpackChunkName: "components__button__index.zh-CN.md" */'/Users/xiaozisong/Desktop/opensource/amenity-ui/components/button/index.zh-CN.md')),
'components/iconselect/index.zh-CN': React.lazy(() => import(/* webpackChunkName: "components__iconselect__index.zh-CN.md" */'/Users/xiaozisong/Desktop/opensource/amenity-ui/components/iconselect/index.zh-CN.md')),
'components/inputnumber/index.zh-CN': React.lazy(() => import(/* webpackChunkName: "components__inputnumber__index.zh-CN.md" */'/Users/xiaozisong/Desktop/opensource/amenity-ui/components/inputnumber/index.zh-CN.md')),
'components/overview/index.zh-CN': React.lazy(() => import(/* webpackChunkName: "components__overview__index.zh-CN.md" */'/Users/xiaozisong/Desktop/opensource/amenity-ui/components/overview/index.zh-CN.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/xiaozisong/Desktop/opensource/amenity-ui/node_modules/.pnpm/dumi@2.3.0-beta.8_borxkdqnsj666zm5xafhs5jqdq/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
