// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/xiaozisong/Desktop/opensource/amenity-ui/node_modules/.pnpm/dumi@2.3.0-beta.8_glxuhseaxnynb3wl34vdbiopru/node_modules/dumi/theme-default/slots/Logo/index.js';
