// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { getSketchJSON } from '/Users/xiaozisong/Desktop/opensource/amenity-ui/.dumi/tmp/plugin-html2sketch';
// plugins types.d.ts
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/xiaozisong/Desktop/opensource/amenity-ui/node_modules/.pnpm/@umijs+renderer-react@4.1.6_ef5jwxihqo6n7gxfmzogljlgcm/node_modules/@umijs/renderer-react';
export type { History } from '/Users/xiaozisong/Desktop/opensource/amenity-ui/node_modules/.pnpm/@umijs+renderer-react@4.1.6_ef5jwxihqo6n7gxfmzogljlgcm/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/xiaozisong/Desktop/opensource/amenity-ui/node_modules/.pnpm/umi@4.1.6_rmhi4qidbpgm7v62zjyfoeulru/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
// test
export { TestBrowser } from './testBrowser';
