// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from '/Users/xiaozisong/Desktop/opensource/amenity-ui/.dumi/pages/index-cn/index.tsx?type=frontmatter';
import { frontmatter as fm1, toc as t1 } from '/Users/xiaozisong/Desktop/opensource/amenity-ui/.dumi/pages/index/index.tsx?type=frontmatter';
import { frontmatter as fm2, toc as t2 } from '/Users/xiaozisong/Desktop/opensource/amenity-ui/docs/spec/introduce.zh-CN.md?type=frontmatter';
import { demoIndex as dmi2 } from '/Users/xiaozisong/Desktop/opensource/amenity-ui/docs/spec/introduce.zh-CN.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from '/Users/xiaozisong/Desktop/opensource/amenity-ui/docs/resources.zh-CN.md?type=frontmatter';
import { demoIndex as dmi3 } from '/Users/xiaozisong/Desktop/opensource/amenity-ui/docs/resources.zh-CN.md?type=demo-index';
import { frontmatter as fm4, toc as t4 } from '/Users/xiaozisong/Desktop/opensource/amenity-ui/docs/spec/test.md?type=frontmatter';
import { demoIndex as dmi4 } from '/Users/xiaozisong/Desktop/opensource/amenity-ui/docs/spec/test.md?type=demo-index';
import { frontmatter as fm5, toc as t5 } from '/Users/xiaozisong/Desktop/opensource/amenity-ui/components/button/index.zh-CN.md?type=frontmatter';
import { demoIndex as dmi5 } from '/Users/xiaozisong/Desktop/opensource/amenity-ui/components/button/index.zh-CN.md?type=demo-index';

export const filesMeta = {
  'index-cn/index': {
    frontmatter: fm0,
    toc: t0,
  },
  'index/index': {
    frontmatter: fm1,
    toc: t1,
  },
  'docs/spec/introduce.zh-CN': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'/Users/xiaozisong/Desktop/opensource/amenity-ui/docs/spec/introduce.zh-CN.md?type=text'),
  },
  'docs/resources.zh-CN': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'/Users/xiaozisong/Desktop/opensource/amenity-ui/docs/resources.zh-CN.md?type=text'),
  },
  'docs/spec/test': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/xiaozisong/Desktop/opensource/amenity-ui/docs/spec/test.md?type=text'),
  },
  'components/button/index.zh-CN': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'/Users/xiaozisong/Desktop/opensource/amenity-ui/components/button/index.zh-CN.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
