// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from '/Users/xiaozisong/Desktop/opensource/amenity-ui/.dumi/pages/index/index.tsx?type=frontmatter';
import { frontmatter as fm1, toc as t1 } from '/Users/xiaozisong/Desktop/opensource/amenity-ui/docs/spec/test.md?type=frontmatter';
import { demoIndex as dmi1 } from '/Users/xiaozisong/Desktop/opensource/amenity-ui/docs/spec/test.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from '/Users/xiaozisong/Desktop/opensource/amenity-ui/components/button/index.zh-CN.md?type=frontmatter';
import { demoIndex as dmi2 } from '/Users/xiaozisong/Desktop/opensource/amenity-ui/components/button/index.zh-CN.md?type=demo-index';

export const filesMeta = {
  'index/index': {
    frontmatter: fm0,
    toc: t0,
  },
  'docs/spec/test': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/xiaozisong/Desktop/opensource/amenity-ui/docs/spec/test.md?type=text'),
  },
  'components/button/index.zh-CN': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'/Users/xiaozisong/Desktop/opensource/amenity-ui/components/button/index.zh-CN.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
