// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/xiaozisong/Desktop/opensource/amenity-ui/node_modules/.pnpm/dumi-plugin-color-chunk@1.1.0_dumi@2.3.0-beta.8/node_modules/dumi-plugin-color-chunk/es/component/index.js';
